// DO NOT EDIT
// This file is auto generated by scripts/gen-md-types.ts

export const content: Record<string, any[]> = {
	home: [
		{
			slug: "contact",
		},
		{
			slug: "intro",
		},
		{
			slug: "work",
		},
	],
	work: [
		{
			title: "Samscript",
			date: "2024-08-03T00:00:00.000Z",
			slug: "_samscript",
		},
		{
			slug: "artvy",
		},
		{
			slug: "bairesdev",
		},
		{
			slug: "careshift",
		},
		{
			title: "Code setup",
			date: "2024-08-03T00:00:00.000Z",
			slug: "coding-setup",
		},
		{
			slug: "others",
		},
		{
			slug: "suppalyze",
		},
	],
};
