// DO NOT EDIT
// This file is auto generated by scripts/gen-md-types.ts

export const content: Record<string, any[]> = {
	blog: [
		{
			title: "A Short Introduction to React",
			published_at: "2023-02-13T09:13:34.862Z",
			tags: [
				"React",
				"Web Development",
				"introduction",
				"JavaScript",
				"JSX",
			],
			slug: "a-short-introduction-to-react",
		},
		{
			title: "Beginner's guide to monorepos and turborepo.",
			published_at: "2023-12-09T11:41:07.844Z",
			tags: [
				"turborepo",
				"monorepo",
				"development",
				"JavaScript",
				"TypeScript",
			],
			slug: "beginners-guide-to-monorepos-and-turborepo",
		},
		{
			title: "building a browser-native react playground",
			published_at: "2026-05-11T00:00:00.000Z",
			tags: ["React", "Compilers", "Web Development"],
			slug: "browser-react-preview",
		},
		{
			title: "Build and deploy a chat application using Socket.io and Redis.",
			published_at: "2024-08-26T10:37:34.985Z",
			tags: [
				"SocketIO",
				"render",
				"GCP",
				"JavaScript",
				"Web Development",
			],
			slug: "build-and-deploy-a-chat-application-using-socketio-and-redis",
		},
		{
			title: "Create dropdown menu (tui) in c",
			published_at: "2025-03-10T05:18:49.542Z",
			tags: ["TUI", "C", "cli"],
			slug: "create-dropdown-menu-tui-in-c",
		},
		{
			title: "Detailed Introduction To Prisma ORM",
			published_at: "2023-09-25T06:54:08.691Z",
			tags: [
				"prisma",
				"Next.js",
				"JavaScript",
				"TypeScript",
				"PostgreSQL",
			],
			slug: "detailed-introduction-to-prisma-orm",
		},
		{
			title: "Everything about Data Fetching & the JavaScript Fetch API.",
			published_at: "2024-03-12T14:54:13.360Z",
			tags: ["JavaScript", "Tutorial", "Web Development"],
			slug: "everything-about-data-fetching-the-javascript-fetch-api",
		},
		{
			title: "How to show progress while downloading data in node.js",
			published_at: "2024-04-27T05:47:26.781Z",
			tags: ["Node.js", "JavaScript", "Beginner Developers"],
			slug: "how-to-show-progress-while-downloading-data-in-nodejs",
		},
		{
			title: "Introduction to Tailwind",
			published_at: "2023-02-17T14:41:22.145Z",
			tags: [
				"Tailwind CSS",
				"Frontend Development",
				"frontend",
				"Web Development",
				"webdev",
			],
			slug: "introduction-to-tailwind",
		},
		{
			title: "JavaScript Datatypes in Detail",
			published_at: "2023-01-08T13:17:59.749Z",
			tags: ["JavaScript", "Web Development", "beginner"],
			slug: "javascript-datatypes-in-detail",
		},
		{
			title: "Learn Git the FAST way.",
			published_at: "2023-01-06T08:12:40.921Z",
			tags: ["Git", "learning"],
			slug: "learn-git-the-fast-way",
		},
		{
			title: "looking forward on 2026",
			published_at: "2026-01-04T17:26:28.589Z",
			slug: "looking-forward-on-2026",
		},
		{
			title: "Regex cheat-sheet.",
			published_at: "2025-10-30T05:21:00.487Z",
			tags: ["Regex", "JavaScript", "Programming Blogs"],
			slug: "regex-cheatsheet",
		},
		{
			title: "Remove trailing spaces in vim.",
			published_at: "2025-10-21T20:28:57.727Z",
			tags: ["vim", "neovim"],
			slug: "remove-trailing-spaces-in-vim",
		},
		{
			title: "The Complete Guide to User Authentication in Firebase",
			published_at: "2023-02-10T11:09:32.999Z",
			tags: ["Firebase", "JavaScript", "Web Development", "webdev"],
			slug: "the-complete-guide-to-user-authentication-in-firebase",
		},
		{
			title: "Vite: The Fast, Simple, and Efficient Build Tool for Web Developers",
			published_at: "2023-02-26T11:30:35.636Z",
			tags: [
				"vite",
				"Build tool",
				"Web Development",
				"webdev",
				"Hot Module Replacement",
			],
			slug: "vite-the-fast-simple-and-efficient-build-tool-for-web-developers",
		},
		{
			title: "Write semantic HTML",
			published_at: "2022-12-16T19:37:29.217Z",
			tags: ["semantichtml", "HTML tags ", "HTML5"],
			slug: "write-semantic-html",
		},
	],
	home: [
		{
			slug: "contact",
		},
		{
			slug: "intro",
		},
		{
			slug: "work",
		},
	],
	work: [
		{
			title: "Samscript",
			date: "2024-08-03T00:00:00.000Z",
			slug: "_samscript",
		},
		{
			slug: "artvy",
		},
		{
			slug: "atomo",
		},
		{
			slug: "bairesdev",
		},
		{
			slug: "careshift",
		},
		{
			title: "Code setup",
			date: "2024-08-03T00:00:00.000Z",
			slug: "coding-setup",
		},
		{
			slug: "maxim-and-bifrost",
		},
		{
			slug: "others",
		},
		{
			slug: "suppalyze",
		},
	],
};
